name: drosophila-scrna-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3.2
  - r-seurat=5.0.1
  - r-dplyr
  - r-ggplot2
  - r-patchwork
  - r-cowplot
  - r-matrix
  - r-scales
  - r-readr
